### ISSUE TITLE
Support for binding YAML parameters to servlets and filters as init parameters

### ISSUE THREAD

**Issue by andrus** [nhl/bootique-jetty#17]
Per #12 developers can supply init parameters to servlets and filters by passing them to the MappedServlet and MappedFilter. This is not very convenient. Would be cool to connect this to YAML. E.g.:

```
jetty:
   servlets:
      s1:
        params:
           a: b
           c: d
   filters:
      f1:
        params:
          f: g
```
This will still require explicitly naming servlets and filters, which will hopefully be easy to achieve after #16 is available.
