### ISSUE TITLE
Support for static resources

### ISSUE THREAD

**Issue by andrus** [nhl/bootique-jetty#18]
This task turns Jetty into a webserver that can serve static files from the filesystem or from the app jar. Static resources can be coming either from classpath, external url or filesystem. Supported configuration:

```
jetty:
  # If true, Jetty will install a "default" servlet that serves static resources.
  # this is "false" by default
  staticResources: true

  # sets a base location for resources of the Jetty context.
  # can be a path, a URL or a special "classpath:/" URL. 
  # it can be reused or overridden by DefaultServlet configuration below.
  # for security reasons this has to be set explicitly. There's no default.
  staticResourceBase: <path_or_url>
```

If "staticResources" is true, Bootique would add Jetty [DefaultServlet](http://download.eclipse.org/jetty/9.3.7.v20160115/apidocs/org/eclipse/jetty/servlet/DefaultServlet.html) to the web server. It supports a bunch of other parameters that can be passed as this:

```
jetty:
  servlets:
    default:
      params:
        resourceBase: a/b/c
        ....
```
