### ISSUE TITLE
Support for context init parameters

### ISSUE THREAD

**Issue by andrus** [nhl/bootique-jetty#19]
While we already support init parameters for servlets and filters, let's also add support for ServletContext params:

```
jetty:
  params:
      a: b
      c: d
```
